2024-02-01 20:47:13.421707: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/luker/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Alpaca orders
                                        id  ...      source
0     9a1427e0-f937-4ab0-9d90-1715e38656ce  ...        None
1     1f69c61f-0b99-4293-bafa-c6eeeab02848  ...  access_key
2     60a4b248-25ba-4f15-82d7-7da7dae823fe  ...  access_key
3     a95ba4a4-1572-40de-bbd8-f0d3667507ff  ...  access_key
4     d9e9bb91-096b-4aca-8bd4-5e953cb31c76  ...  access_key
...                                    ...  ...         ...
4830  103c8e2d-853b-43e1-a1ee-9cc5c8612057  ...  access_key
4831  9a875acf-9a82-4b87-88e2-a2cc2a885047  ...  access_key
4832  a911c399-cd80-4a26-a1de-2004e8e88e43  ...  access_key
4833  2cc0db64-ea9b-4993-b991-813809d9129c  ...  access_key
4834  67c9b8c5-7df6-414e-8f57-70e082021d28  ...  access_key

[4817 rows x 34 columns]
Exception occurred: 
[Errno 104] Connection reset by peer
Counts for buy, sell, hold:  [0, 0, 0]
Traceback (most recent call last):
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 196, in _one_request
    response.raise_for_status()
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/account/portfolio/history?period=5D&timeframe=1D&extended_hours=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luker/anaconda3/envs/trading_env/bin/bot", line 8, in <module>
    sys.exit(main())
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/cli/bot.py", line 26, in main
    bot.start()
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/bot.py", line 151, in start
    plt = plotAlpaca(daysSinceStart.days) # pylint: disable=no-value-for-parameter
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/plotAlpaca.py", line 105, in plotAlpaca
    portHistory=trading_client.get_portfolio_history(filter=portFilter)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/plotAlpaca.py", line 56, in get_portfolio_history
    response = self.get("/account/portfolio/history", params)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 221, in get
    return self._request("GET", path, data, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 129, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 205, in _one_request
    raise APIError(error, http_error)
alpaca.common.exceptions.APIError: {"message": "forbidden."}

