2024-01-29 17:50:44.760348: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/luker/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!
Alpaca orders
Empty DataFrame
Columns: []
Index: []
Exception occurred: 
HTTP Error 524: 
Counts for buy, sell, hold:  [0, 0, 0]
Traceback (most recent call last):
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 196, in _one_request
    response.raise_for_status()
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://paper-api.alpaca.markets/v2/account/portfolio/history?period=2D&timeframe=1D&extended_hours=True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luker/anaconda3/envs/trading_env/bin/bot", line 8, in <module>
    sys.exit(main())
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/cli/bot.py", line 26, in main
    bot.start()
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/bot.py", line 148, in start
    plt = plotAlpaca(daysSinceStart.days) # pylint: disable=no-value-for-parameter
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/plotAlpaca.py", line 105, in plotAlpaca
    portHistory=trading_client.get_portfolio_history(filter=portFilter)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/bot/plotAlpaca.py", line 56, in get_portfolio_history
    response = self.get("/account/portfolio/history", params)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 221, in get
    return self._request("GET", path, data, **kwargs)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 129, in _request
    return self._one_request(method, url, opts, retry)
  File "/home/luker/anaconda3/envs/trading_env/lib/python3.8/site-packages/alpaca/common/rest.py", line 205, in _one_request
    raise APIError(error, http_error)
alpaca.common.exceptions.APIError: {"message": "forbidden."}

